# Generated by Django 3.0.7 on 2020-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('money_min', models.FloatField()),
                ('money_max', models.FloatField(null=True)),
                ('monthly', models.BooleanField(default=True)),
                ('opis', models.TextField(null=True)),
                ('zapasowa', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthsBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_name_of_month', models.CharField(max_length=64, verbose_name='Nazwa jaką chcesz wpisać dla tego miesiąca:')),
                ('month_cost', models.FloatField()),
                ('description', models.CharField(max_length=256, null=True)),
                ('month_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skarbonki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_for', models.CharField(max_length=64)),
                ('m_min', models.FloatField()),
                ('m_max', models.FloatField(null=True)),
                ('month', models.BooleanField(default=True)),
                ('opis', models.TextField(null=True)),
                ('zapas', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
