# Generated by Django 3.0.7 on 2020-06-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('money_min', models.FloatField()),
                ('monthly', models.BooleanField(default=True)),
                ('opis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthsBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_name_of_month', models.CharField(max_length=64, verbose_name='Nazwa jaką chcesz wpisać dla tego miesiąca:')),
                ('month_cost', models.FloatField()),
                ('description', models.CharField(max_length=256, null=True)),
                ('month_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skarbonki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_for', models.CharField(max_length=64)),
                ('m_min', models.FloatField()),
                ('m_max', models.FloatField(null=True)),
                ('month', models.BooleanField(default=True)),
                ('opis', models.TextField(null=True)),
                ('zapas', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enter_price', models.FloatField()),
                ('interests', models.IntegerField()),
                ('value_of', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('dividend', models.NullBooleanField(default=False)),
                ('type_of_market', models.CharField(max_length=64, null=True)),
                ('www', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(auto_now_add=True)),
                ('payment_collected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.AlreadyCollected')),
                ('payment_skarbonki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Skarbonki')),
            ],
        ),
        migrations.AddField(
            model_name='alreadycollected',
            name='target',
            field=models.ManyToManyField(through='budget_app.PaymentDay', to='budget_app.Skarbonki'),
        ),
    ]
