# Generated by Django 3.0.7 on 2020-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enter_price', models.FloatField()),
                ('interests', models.IntegerField()),
                ('value_of', models.FloatField()),
                ('price', models.FloatField()),
                ('dividend', models.NullBooleanField(default=False)),
                ('type_of_market', models.CharField(max_length=64)),
            ],
        ),
    ]
