# Generated by Django 3.0.7 on 2020-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='www',
            field=models.CharField(default='www.pl', max_length=256),
            preserve_default=False,
        ),
    ]
