# Generated by Django 3.0.7 on 2020-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_auto_20200620_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skarbonki',
            name='m_max',
        ),
        migrations.RemoveField(
            model_name='skarbonki',
            name='month',
        ),
        migrations.RemoveField(
            model_name='skarbonki',
            name='zapas',
        ),
    ]
