# Generated by Django 3.0.7 on 2020-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_stock_www'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type_of_market',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value_of',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='www',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
