# Generated by Django 3.0.7 on 2020-06-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20200621_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='money_min',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='paymentday',
            old_name='payment_skarbonki',
            new_name='payment_piggybanks',
        ),
        migrations.RenameField(
            model_name='skarbonki',
            old_name='opis',
            new_name='description',
        ),
    ]
