# Generated by Django 3.0.7 on 2020-06-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20200622_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skarbonki',
            new_name='PiggyBanks',
        ),
    ]
