# Generated by Django 3.0.7 on 2020-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_auto_20200622_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_income', models.CharField(max_length=128, verbose_name='Nazwa dla dochodu')),
                ('value_of_income', models.FloatField(verbose_name='Kwota dochodu')),
                ('income_description', models.TextField(null=True, verbose_name='Opis dochodu')),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis zobowiązania'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='money',
            field=models.FloatField(verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly',
            field=models.BooleanField(default=True, verbose_name='Czy to koszt comiesięczny?'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='credit_amount',
            field=models.FloatField(verbose_name='Kwota kredytu'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='description',
            field=models.TextField(null=True, verbose_name='Opcjonalny opis'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa dla kredytu'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='should_end_on',
            field=models.DateField(null=True, verbose_name='Data planowanej końcowej spłaty'),
        ),
        migrations.AlterField(
            model_name='monthsbudget',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='Opcjonalny opis'),
        ),
        migrations.AlterField(
            model_name='monthsbudget',
            name='month_cost',
            field=models.FloatField(verbose_name='Miesięczne koszty'),
        ),
        migrations.AlterField(
            model_name='piggybanks',
            name='description',
            field=models.TextField(null=True, verbose_name='Opcjonalny opis dla celu'),
        ),
        migrations.AlterField(
            model_name='piggybanks',
            name='m_min',
            field=models.FloatField(verbose_name='Kwota potrzebna na ten cel'),
        ),
        migrations.AlterField(
            model_name='piggybanks',
            name='money_for',
            field=models.CharField(max_length=64, verbose_name='Nazwa dla określonego celu'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.NullBooleanField(default=False, verbose_name='Czy jest wypłacana dywidenda?'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='enter_price',
            field=models.FloatField(verbose_name='Cena w momencie zakupu'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='interests',
            field=models.IntegerField(verbose_name='Liczba zakupionych udziałów'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa dla określonej akcji'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True, verbose_name='Cena, jaką chcesz zapisać'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type_of_market',
            field=models.CharField(max_length=64, null=True, verbose_name='Nazwa dla rodzaju rynku akcji'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value_of',
            field=models.FloatField(null=True, verbose_name='Wartość, którą chcesz wpisać'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='www',
            field=models.CharField(max_length=256, null=True, verbose_name='Link do strony internetowej inwestora dla akcji'),
        ),
    ]
