# Generated by Django 3.0.7 on 2020-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_auto_20200627_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_name', models.CharField(max_length=64, verbose_name='Nazwa dla dodatkowego przychodu')),
                ('amount_only', models.FloatField(verbose_name='Zapisywana kwota dodatkowa (*można pozostawić wolne)')),
                ('amount_with_monthly', models.FloatField(verbose_name='Kwota dodatkowa wraz z miesięcznymi wpływami (*można pozostawić wolne)')),
                ('income_description', models.CharField(max_length=128, verbose_name='Opis dla wpisywanego dodatkowego przychodu')),
                ('income_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='credits',
            name='should_end_on',
            field=models.DateField(null=True, verbose_name='Planowana końcowa spłata (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_description',
            field=models.TextField(null=True, verbose_name='Opcjonalny opis'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name_of_income',
            field=models.CharField(max_length=128, verbose_name='Nazwa dla przychodu'),
        ),
        migrations.AlterField(
            model_name='income',
            name='value_of_income',
            field=models.FloatField(verbose_name='Kwota wpływu'),
        ),
    ]
