# Generated by Django 3.0.7 on 2020-07-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_auto_20200701_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='value_of',
        ),
    ]
