# Generated by Django 3.0.7 on 2020-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_auto_20200701_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='value_of',
            field=models.FloatField(null=True, verbose_name='Wartość początkowa zakupu udziałów'),
        ),
    ]
