# Generated by Django 4.0.2 on 2022-02-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0012_stock_value_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.BooleanField(default=False, null=True, verbose_name='Czy jest wypłacana dywidenda?'),
        ),
    ]
